name: kyb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  barcode_scan2: ^4.3.3
  http: ^1.2.2
  html: ^0.15.5
  firebase_core: ^3.6.0
  get: ^4.6.6
  firebase_auth: ^5.3.2
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.5
  dio: ^5.7.0
  collection: ^1.18.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Added for app icon generation

flutter:
  uses-material-design: true
  assets:
    - assets/1.jpg
    - assets/logo.jpeg
    - assets/placeholder_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg" # Path to your app logo
  min_sdk_android: 21